JSONMockBundle\Entity\Application:
    type: entity
    table: application
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        secret:
            column: secret
            type: string
            unique: true
            nullable: false
            length: 255
            options:
                fixed: false
        name:
            column: name
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    oneToMany:
        responses:
            targetEntity: Response
            mappedBy: application
            cascade: [ persist ]

    lifecycleCallbacks: {  }