JSONMockBundle\Entity\Response:
    type: entity
    table: response
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        value:
            column: value
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
        method:
            column: method
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        statusCode:
            column: status_code
            type: integer
            nullable: false
            options:
                fixed: false
    manyToOne:
        application:
            targetEntity: Application
            inversedBy: response
            joinColumn:
                    name: application_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }