api_application_get:
  path: application/{app_key}.{_format}
  defaults:  { _controller: RestApiBundle:Application:getApplication, _format: json }
  methods: [GET]

api_application_create:
  path: application.{_format}
  defaults:  { _controller: RestApiBundle:Application:createApplication, _format: json }
  methods: [POST]

api_application_edit:
  path: application/{app_key}.{_format}
  defaults:  { _controller: RestApiBundle:Application:editApplication, _format: json }
  methods:  [PUT]

api_application_delete:
  path: application/{app_key}.{_format}
  defaults:  { _controller: RestApiBundle:Application:deleteApplication, _format: json }
  methods: [DELETE]