api_application:
  prefix: /api/app/
  resource: "@RestApiBundle/Resources/config/api/application.yml"

response _get:
  path: /app/{app_key}/{response_name}.{_format}
  defaults:  { _controller: RestApiBundle:Response:getResponse, _format: json }
  methods: [GET]
