api_application:
  prefix: /api/app/
  resource: "@RestApiBundle/Resources/config/api/application.yml"

response _get:
  path: /app/{app_key}/{param}.{_format}
  defaults:  { _controller: RestApiBundle:Response:getResponse, _format: json, param1: null, param2: null, param3: null}
  methods: [GET]
  requirements:
    param: .+
